packages:
  - ./app
  - ./infra/cognito

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

overrides:
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'

strictPeerDependencies: false
