packages:
  - ./app
  - ./infra/cognito

engineStrict: true

### https://thedaviddias.dev/notes/how-to-fix-post-pre-build-pnpm
enablePrePostScripts: true

strictPeerDependencies: false

legacyPeerDeps: true
autoInstallPeers: true
