packages:
  - ./app
  - ./infra/cognito

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

overrides:
  fast-xml-parser@>=4.0.0-beta.3 <=5.5.5: '>=5.5.6'
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
