packages:
  - ./app
  - ./infra/cognito

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

overrides:
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'

strictPeerDependencies: false
