packages:
  - ./app
  - ./infra/cognito

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

overrides:
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
